<?php
include('../detect.php');
include('../settings.php');
if ($pais_multilang == 'lang_active') {
	if ($negara == 'GB') {
		$title = 'Log in to your PayPal account';
		$otherwise = 'Already set up to use your phone number to log in? Type it below. Otherwise, click the link to log in with email.';
		$email = 'Email';
		$password = 'Password';
		$change = 'Change';
		$troublelogin = 'Having trouble logging in?';
		$or = 'or';
		$next = 'Next';
		$signup = 'Sign Up';
		$login = 'Login';
		$privacy = 'Privacy';
		$legal = 'Legal';
		$copyright = 'Copyright © 1999-2018 PayPal. All rights reserved.';
		$pp = "Consumer advisory - PayPal Pte. Ltd., the holder of PayPal's stored value facility, does not require the approval of the Monetary Authority of Singapore. Users are advised to read the <a href='#' pa-tracked='1'>terms and conditions</a> carefully.";
		$waitmoment = 'One moment...';
		$tryagain = 'Still loading after a few seconds?';
		$link = 'Try again';
	}elseif ($negara == 'JP') {
		$title = 'PayPalアカウントへのログイン';
		$otherwise = 'Already set up to use your phone number to log in? Type it below. Otherwise, click the link to log in with email.';
		$email = 'メールアドレス';
		$password = 'パスワード';
		$change = '変更';
		$troublelogin = 'ログインできない場合';
		$next = '次へ';
		$or = 'または';
		$signup = '新規登録';
		$login = 'ログイン';
		$privacy = 'プライバシー';
		$legal = '規約';
		$copyright = 'Copyright © 1999-2018 PayPal. All rights reserved.';
		$pp = "消費者の皆様へのご注意 - PayPalのストアドバリュー設備の所有者であるPayPal Pte. Ltd.は、シンガポール通貨金融庁(Monetary Authority of Singapore)の承認を必要としません。ご利用の際には、<a href='#'' pa-tracked='1'>契約条件</a>をよくご確認ください。";
		$waitmoment = '一瞬...';
		$tryagain = '数秒後にまだ読み込んでいますか？';
		$link = '再試行する';
	}elseif ($negara == 'CN') {
		$title = '登录您的PayPal账户';
		$otherwise = 'Already set up to use your phone number to log in? Type it below. Otherwise, click the link to log in with email.';
		$email = '邮箱地址';
		$password = '密码';
		$change = '更改';
		$troublelogin = '无法登录？';
		$next = '下一步';
		$or = '或者';
		$signup = '注册';
		$login = '登录';
		$privacy = '隐私权';
		$legal = '法律协议';
		$copyright = '版权所有© 1999-2018 PayPal。保留所有权利。';
		$pp = "消费者提示——PayPal Pte. Ltd.系PayPal储值工具的持有者，不需要经过新加坡金融管理局的批准。建议用户仔细阅读<a href='#'' pa-tracked='1'>条款和条件</a>";
		$waitmoment = '一会儿...';
		$tryagain = '几秒钟后还在加载？';
		$link = '再试一次';
	}elseif ($negara == 'HU') {
		$title = 'Bejelentkezés a PayPal-számlára';
		$otherwise = 'Already set up to use your phone number to log in? Type it below. Otherwise, click the link to log in with email.';
		$email = 'E-mail-cím';
		$password = 'Jelszó';
		$change = 'Módosítás';
		$troublelogin = 'Problémája van a bejelentkezéssel?';
		$or = 'vagy';
		$next = 'Tovább';
		$signup = 'Regisztráció';
		$login = 'Bejelentkezés';
		$privacy = 'Adatvédelem';
		$legal = 'PayPal';
		$copyright = 'Copyright ©1999-2018 PayPal. Minden jog fenntartva..';
		$pp = "";
		$waitmoment = 'One moment...';
		$tryagain = 'Still loading after a few seconds?';
		$link = 'Try again';
	}elseif($negara == 'IT'){
		$title = 'Accedi al tuo account PayPal';
		$otherwise = 'Sei già configurato per utilizzare il tuo numero di telefono per accedere? Digita di seguito. Altrimenti, fai clic sul link per accedere con la posta elettronica.';
		$email = 'Indirizzo email';
		$password = "Parola d'ordine";
		$change = 'Modificare';
		$troublelogin = 'Hai problemi ad accedere?';
		$or = 'o';
		$next = 'Continua';
		$signup = 'Iscriviti';
		$login = 'Accedi';
		$privacy = 'vita privata';
		$legal = 'legale';
		$copyright = 'Copyright © 1999-2018 PayPal. Tutti i diritti riservati.';
		$pp = '';
		$waitmoment = 'Un momento...';
		$tryagain = 'Ancora carico dopo pochi secondi?';
		$link = 'Riprova';
	}elseif($negara == 'KR'){
		$title = 'PayPal 계정에 로그인하십시오.';
		$otherwise = '이미 전화 번호를 사용하여 로그인하도록 설정 했습니까? 아래에 입력하십시오. 그렇지 않으면 링크를 클릭하여 이메일로 로그인하십시오.';
		$email = '이메일 주소';
		$password = '암호';
		$change = '변화';
		$troublelogin = '로그인하는 데 문제가 있습니까?';
		$or = '또는';
		$next = '다음 것';
		$signup = '가입하기';
		$login = '로그인';
		$privacy = '은둔';
		$legal = '적법한';
		$copyright = '저작권 © 1999-2018 PayPal. 판권 소유.';
		$pp = "소비자 자문 - PayPal Pte. Ltd.는 PayPal의 저장 가치 시설 보유자로서 싱가포르의 통화 당국의 승인을 요구하지 않습니다. 사용자는 신중하게 <a href='#'pa-tracked='1'> 이용 약관 </a>을 읽어 보시기 바랍니다.";
		$waitmoment = '잠시만...';
		$tryagain = '몇 초 후에 여전히로드 중입니까?';
		$link = '다시 시도하십시오.';
	}elseif ($negara == 'NL') {
		$title = 'Log in op uw PayPal-rekening';
		$otherwise = 'Ben je al ingesteld om je telefoonnummer te gebruiken om in te loggen? Type het hieronder. Klik anders op de link om u aan te melden met e-mail.';
		$email = 'E-mailadres';
		$password = 'Wachtwoord';
		$change = 'Verandering';
		$troublelogin = 'heb je problemen met inloggen?';
		$or = 'of';
		$next = 'volgende';
		$signup = 'Aanmelden';
		$login = 'Inloggen';
		$privacy = 'Privacy';
		$legal = 'wettelijk';
		$copyright = 'Copyright © 1999-2018 PayPal. Alle rechten voorbehouden.';
		$pp = "Consumentenadvies - PayPal Pte. Ltd., de houder van de opgeslagen waarderingsfaciliteit van PayPal, vereist geen goedkeuring van de Monetaire Autoriteit van Singapore. Gebruikers worden geadviseerd om de <a href='#' pa-tracked='1'> algemene voorwaarden </a> aandachtig te lezen.";
		$waitmoment = 'Een moment...';
		$tryagain = 'Nog steeds laden na een paar seconden?';
		$link = 'Probeer het nog eens';
	}elseif ($negara == 'PH') {
		$title = 'Mag-log in sa iyong PayPal account';
		$otherwise = 'Na-set up upang gamitin ang iyong numero ng telepono upang mag-log in? I-type ito sa ibaba. Kung hindi, i-click ang link upang mag-log in gamit ang email.';
		$email = 'Email';
		$password = 'Password';
		$change = 'Baguhin';
		$troublelogin = 'Nagkakaproblema sa pag-log in?';
		$or = 'o';
		$next = 'Susunod';
		$signup = 'Mag-sign up';
		$login = 'Mag-login';
		$privacy = 'Privacy';
		$legal = 'Legal';
		$copyright = 'Copyright © 1999-2018 PayPal. Lahat ng karapatan ay nakalaan.';
		$pp = "Konsulta ng mamimili - PayPal Pte. Ltd, ang may-ari ng pasilidad na naka-imbak na halaga ng PayPal, ay hindi nangangailangan ng pag-apruba ng Monetary Authority of Singapore. Pinapayuhan ang mga gumagamit na basahin ang <a href='#' pa-tracked='1'> mga tuntunin at kundisyon </a> nang maingat.";
		$waitmoment = 'Isang sandali...';
		$tryagain = 'Naglo-load pa pagkatapos ng ilang segundo?';
		$link = 'Subukan muli';
	}else{
		$title = 'Log in to your PayPal account';
		$otherwise = 'Already set up to use your phone number to log in? Type it below. Otherwise, click the link to log in with email.';
		$email = 'Email';
		$password = 'Password';
		$change = 'Change';
		$troublelogin = 'Having trouble logging in?';
		$or = 'or';
		$next = 'Next';
		$signup = 'Sign Up';
		$login = 'Login';
		$privacy = 'Privacy';
		$legal = 'Legal';
		$copyright = 'Copyright © 1999-2018 PayPal. All rights reserved.';
		$pp = "Consumer advisory - PayPal Pte. Ltd., the holder of PayPal's stored value facility, does not require the approval of the Monetary Authority of Singapore. Users are advised to read the <a href='#' pa-tracked='1'>terms and conditions</a> carefully.";
		$waitmoment = 'One moment...';
		$tryagain = 'Still loading after a few seconds?';
		$link = 'Try again';
	}
}else{
	$title = 'Log in to your PayPal account';
	$otherwise = 'Already set up to use your phone number to log in? Type it below. Otherwise, click the link to log in with email.';
	$email = 'Email';
	$password = 'Password';
	$change = 'Change';
	$troublelogin = 'Having trouble logging in?';
	$or = 'or';
	$next = 'Next';
	$signup = 'Sign Up';
	$login = 'Login';
	$privacy = 'Privacy';
	$legal = 'Legal';
	$copyright = 'Copyright © 1999-2018 PayPal. All rights reserved.';
	$pp = "Consumer advisory - PayPal Pte. Ltd., the holder of PayPal's stored value facility, does not require the approval of the Monetary Authority of Singapore. Users are advised to read the <a href='#' pa-tracked='1'>terms and conditions</a> carefully.";
	$waitmoment = 'One moment...';
	$tryagain = 'Still loading after a few seconds?';
	$link = 'Try again';
}
?>